In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
folder_name = 'orderline_price_asin_small'

In [3]:
### load_xml_query
xml_query_file_path = "data/" + folder_name + "/" + "XML_query.dat"
with open(xml_query_file_path) as f:
    content = f.readlines()
content = [x.strip() for x in content]

all_elements_name = content[0].split(" ")

relationship_matrix = np.zeros((len(all_elements_name), len(all_elements_name)))

for i in range(1, len(content)):
    relationship = content[i].split(" ")
    relationship_matrix[all_elements_name.index(relationship[0]), all_elements_name.index(relationship[1])] = int(relationship[2])

In [4]:
### load_tables
tables_name = []
tables_content = {}
for file_name in os.listdir("./data/" + folder_name):
    if 'table' in file_name:
        table_name = file_name[:-10]
        tables_name.append(table_name)
        tables_content[table_name] = pd.read_csv('./data/' + folder_name + '/' + file_name, names = table_name.split('_'), sep='\s+')

In [5]:
### load elements
elements_value = {}
for element_name in all_elements_name:
    path = "data/" + folder_name + "/" + element_name + "_v.dat"
    elements_value[element_name] = pd.read_csv(path, names = [element_name], sep='\s+')
elements_value

{'Orderline':        Orderline
 0           8357
 1          43921
 2          44502
 3          31464
 4          47075
 5          25158
 6          37060
 7          27574
 8          13844
 9          44353
 10         40342
 11         49061
 12         12154
 13          7765
 14         36807
 15         16480
 16         38102
 17          7311
 18         15449
 19         17098
 20         45272
 21         28099
 22          9678
 23         48336
 24         47090
 25         49270
 26         40882
 27         13302
 28         10412
 29         28266
 ...          ...
 9989       15609
 9990       37979
 9991       47933
 9992       49987
 9993       26920
 9994       44810
 9995        8702
 9996       46185
 9997       36825
 9998       40297
 9999        5567
 10000      43526
 10001      49824
 10002      26686
 10003      45599
 10004      26225
 10005      25477
 10006      18680
 10007      15735
 10008       9916
 10009      37210
 10010      10107
 10011      27567
 10012      39338
 10013      20493
 10014      47635
 10015      20322
 10016      29166
 10017      12576
 10018      10169

 [10019 rows x 1 columns], 'asin':         asin
 0      69104
 1      29010
 2      60748
 3      53388
 4      32223
 5      49869
 6      61365
 7      93246
 8      16193
 9      94000
 10     74566
 11     30287
 12     22045
 13     82989
 14     27994
 15     73489
 16     44554
 17     27835
 18     38938
 19     69048
 20     64080
 21     72491
 22     16552
 23     51184
 24     77844
 25     66870
 26     53039
 27     52258
 28     55465
 29     38328
 ...      ...
 10355  91954
 10356  79728
 10357  54038
 10358  68840
 10359  43277
 10360  25609
 10361  29367
 10362  41612
 10363  33018
 10364  18746
 10365  90164
 10366  73837
 10367  97441
 10368  61325
 10369  59599
 10370  80449
 10371  77409
 10372  46516
 10373  91622
 10374  14530
 10375  10967
 10376  31543
 10377  93773
 10378  14205
 10379  18517
 10380  24161
 10381  67942
 10382  11302
 10383  55779
 10384  51170

 [10385 rows x 1 columns], 'price':         price
 0      106641
 1       70775
 2       47698
 3       77242
 4      196321
 5       50867
 6       23771
 7       10347
 8      192688
 9      107740
 10      36714
 11      37491
 12     110921
 13      74294
 14      21241
 15      30484
 16      94533
 17      37379
 18      76485
 19      21559
 20      93292
 21      52530
 22      66583
 23      59343
 24      29685
 25     149520
 26      35940
 27     143790
 28     154377
 29     109817
 ...       ...
 10395  175061
 10396   72060
 10397  128730
 10398   47190
 10399   48366
 10400  188687
 10401   16304
 10402   95284
 10403  111601
 10404  157695
 10405   98946
 10406  155654
 10407  185203
 10408   14907
 10409   98760
 10410   74208
 10411   52861
 10412   56605
 10413   45142
 10414  188649
 10415   76387
 10416  171571
 10417  181872
 10418  110516
 10419  119332
 10420  164660
 10421  154146
 10422   92526
 10423   51859
 10424  105752

 [10425 rows x 1 columns]}

In [9]:
def print_statistical_overview(series, tab_index = 1):
    print('\t' * tab_index, 'n:', len(series.as_matrix()))
    print('\t' * tab_index, 'mean:', np.mean(series.as_matrix()))
    print('\t' * tab_index, 'std:', np.std(series.as_matrix()))

In [17]:
print('ELEMENTS: ', ', '.join(all_elements_name))
print('TABLES: ', ', '.join(tables_name))

ELEMENTS:  Orderline, price, asin
TABLES:  Orderline_asin, price_asin

In [10]:
for element in all_elements_name:
    print('XML overview:', element)
    print_statistical_overview(elements_value[element][element])
    print('Table containing element')
    for table in tables_name:
        if element in table:
            print('\t', table)
            print_statistical_overview(tables_content[table][element], 2)

XML overview: Orderline
	 n: 10019
	 mean: 27684.367801177763
	 std: 13018.356691302306
Table containing element
	 Orderline_asin
		 n: 10000
		 mean: 27810.3737
		 std: 12963.192261840766
XML overview: price
	 n: 10425
	 mean: 103811.1932853717
	 std: 54921.119616914206
Table containing element
	 price_asin
		 n: 10000
		 mean: 105064.2509
		 std: 55043.50171755563
XML overview: asin
	 n: 10385
	 mean: 54514.34790563313
	 std: 26145.955017854452
Table containing element
	 Orderline_asin
		 n: 10000
		 mean: 54983.4764
		 std: 26043.706101352836
	 price_asin
		 n: 10000
		 mean: 54713.4991
		 std: 25959.531070907255